# Runs inside the TortOS toolchain container. CC comes from the image; SYSROOT
# is passed in and holds the device's own SDL2 libraries, so what links is
# byte-identical to what runs.
BUILD := build
# One device file per build: src/platform_brick.c or src/platform_gkd.c, never
# both - they define the same functions. The Makefile passes PLATFORM and, for
# the GKD, BUILD=build/gkd.
PLATFORM ?= brick
SRC := $(filter-out src/platform_%.c,$(wildcard src/*.c)) src/platform_$(PLATFORM).c
CC ?= aarch64-linux-gnu-gcc

VERSION ?= 0.0
CFLAGS := -DTORTOS_VERSION='"$(VERSION)"' -O2 -mcpu=cortex-a53 -Wall -Wextra -Wno-unused-parameter -std=gnu11 \
          -I$(SYSROOT)/usr/include/SDL2 -D_GNU_SOURCE
ifeq ($(PLATFORM),gkd)
# The one use outside the device files: bt.c, wifi.c and btvol.c keep their
# host stubs on the GKD until it has radio code of its own (gkd.9, gkd.10).
CFLAGS += -DPLATFORM_GKD
endif
# --allow-shlib-undefined: the device's SDL2_ttf pulls FT_* out of freetype,
# and SDL2/SDL2_image reach for more of the firmware besides. Those resolve on
# the device at runtime, where they exist. The flag permits undefined symbols
# in SHARED LIBRARIES only - anything THIS code calls and cannot find is still
# a link error, which is what makes the link a real check that TortOS uses no
# SDL function the shipped libraries lack.
LDFLAGS := -L$(SYSROOT)/usr/lib -Wl,-rpath-link,$(SYSROOT)/usr/lib \
           -Wl,--allow-shlib-undefined
LDLIBS := -lSDL2 -lSDL2_image -lSDL2_ttf -lm -ldl
ifeq ($(PLATFORM),gkd)
# The volume worker (platform_gkd.c). glibc 2.31 here still has it apart from
# libc; the device's 2.40 keeps libpthread.so.0 as a stub, so it resolves.
LDLIBS += -lpthread
endif

# The ScreenScraper developer pair, from the environment into a GENERATED
# HEADER rather than onto the compile line.
#
# -DSS_DEVPASS='"..."' would work and would put the password in an argument
# make echoes on every build, into the terminal and into any log the build is
# piped to. The header goes under $(BUILD), which is gitignored, is written
# with a 077 umask, and is replaced only when its contents change so an
# unchanged environment does not force a relink.
#
# AN UNSET ENVIRONMENT IS A SUPPORTED BUILD. Both come out empty, ss_have_dev()
# is false, and the launcher scrapes from libretro alone - so a stranger
# cloning this repository gets a launcher that works. The credentials are never
# committed; see BACKLOG 31 for why that is the whole of the protection and
# what it does not buy.
CREDS := $(BUILD)/ss_creds.h
CFLAGS += -I$(BUILD)

TP_OUT := $(BUILD)/tp
TP_OPT := -O2 -mcpu=cortex-a53
include mk/third_party.mk
CFLAGS += $(TP_CFLAGS)

.PHONY: creds
creds:
	@mkdir -p $(BUILD)
	@umask 077; { \
	  echo '/* Generated by the build from the environment. Not in the'; \
	  echo '   repository, and not a secret from anyone holding the card:'; \
	  echo '   see BACKLOG 31. */'; \
	  printf '#define SS_DEVID   "%s"\n' "$$(printf '%s' "$$SS_DEVID"   | sed 's/[\\"]/\\\\&/g')"; \
	  printf '#define SS_DEVPASS "%s"\n' "$$(printf '%s' "$$SS_DEVPASS" | sed 's/[\\"]/\\\\&/g')"; \
	} > $(CREDS).new
	@cmp -s $(CREDS).new $(CREDS) 2>/dev/null || mv -f $(CREDS).new $(CREDS)
	@rm -f $(CREDS).new

$(BUILD)/tortos.elf: $(SRC) $(CREDS) $(wildcard src/*.h) $(TP_OBJ)
	mkdir -p $(BUILD)
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $(SRC) $(TP_OBJ) $(LDLIBS)

# A libc-only helper with no SDL: setbright puts the panel at the configured
# brightness before the boot animation, while the launcher is still starting.
# Muse, the audio player's engine: a second binary, like setbright, and not
# part of tortos.elf - SRC above is src/*.c, which does not descend into
# src/muse/. Linked against the device's own FFmpeg 6.1 (mk/fetch-sysroot.sh
# puts the libraries and the matching headers in the sysroot); ALSA is reached
# with dlopen, so it needs no header and no -lasound.
MUSE_SRC := $(wildcard src/muse/*.c)
$(BUILD)/muse: $(MUSE_SRC) $(wildcard src/muse/*.h)
	mkdir -p $(BUILD)
	$(CC) -O2 -mcpu=cortex-a53 -Wall -Wextra -Wno-unused-parameter -std=gnu11 \
	      -D_GNU_SOURCE -I$(SYSROOT)/usr/include $(LDFLAGS) -o $@ $(MUSE_SRC) \
	      -lavformat -lavcodec -lavfilter -lswresample -lavutil -lpthread -ldl

# Talks to Muse by hand over ssh; the device's BusyBox nc has no -U.
$(BUILD)/musectl: tools/musectl.c
	mkdir -p $(BUILD)
	$(CC) -O2 -mcpu=cortex-a53 -Wall -Wextra -std=gnu11 -o $@ $<

# Registers a do-nothing media player with BlueZ so a headset's absolute
# volume is not dropped; see the file. libdbus by dlopen, like ALSA in Muse.
$(BUILD)/btplayer: tools/btplayer.c
	mkdir -p $(BUILD)
	$(CC) -O2 -mcpu=cortex-a53 -Wall -Wextra -std=gnu11 -o $@ $< -ldl

$(BUILD)/setbright: tools/setbright.c
	mkdir -p $(BUILD)
	$(CC) -O2 -mcpu=cortex-a53 -Wall -std=gnu11 -o $@ $<

# A libc-only probe, no SDL. It dlopens the device's own libsqlite3 rather than
# linking it, because there is no sqlite3.h on the device or in the sysroot.
$(BUILD)/storeprobe: tools/storeprobe.c
	mkdir -p $(BUILD)
	$(CC) -O2 -mcpu=cortex-a53 -Wall -Wextra -std=gnu11 -o $@ $< -ldl
