# Native dev build (macOS/Linux host): make -f mk/native.mk
#
# Drivable with the arrow keys, Return and Escape. Point it at a staging tree:
#   TORTOS_ROOT=... TORTOS_ROMS=... TORTOS_FONT=res/fonts/menu.ttf build-native/tortos
# There is no emulator on the host, so launching a game does nothing useful --
# this build is for looking at the shelf while changing how it looks.
BUILD := build-native
# The Brick's device file: its not-__linux__ branches are the host stubs.
SRC := $(filter-out src/platform_%.c,$(wildcard src/*.c)) src/platform_brick.c

PKGS := sdl2 SDL2_image SDL2_ttf
VERSION ?= 0.0
# A different VERSION from the last build's deletes the binary. See Makefile.
ifneq ($(VERSION),$(shell cat $(BUILD)/version 2>/dev/null))
$(shell mkdir -p $(BUILD) && rm -f $(BUILD)/tortos && echo '$(VERSION)' > $(BUILD)/version)
endif
CFLAGS := -DTORTOS_VERSION='"$(VERSION)"' -O1 -g -Wall -Wextra -Wno-unused-parameter -std=gnu11 -D_GNU_SOURCE \
          $(shell pkg-config --cflags $(PKGS))
LDLIBS := $(shell pkg-config --libs $(PKGS)) -lm

# The same generated header the device build uses, for the same reason, so the
# host build can talk to ScreenScraper too. See mk/cross.mk.
CREDS := $(BUILD)/ss_creds.h
CFLAGS += -I$(BUILD)

.PHONY: all creds
all: creds $(BUILD)/tortos

creds:
	@mkdir -p $(BUILD)
	@umask 077; { \
	  echo '/* Generated by the build from the environment. See BACKLOG 31. */'; \
	  printf '#define SS_DEVID   "%s"\n' "$$(printf '%s' "$$SS_DEVID"   | sed 's/[\\"]/\\\\&/g')"; \
	  printf '#define SS_DEVPASS "%s"\n' "$$(printf '%s' "$$SS_DEVPASS" | sed 's/[\\"]/\\\\&/g')"; \
	} > $(CREDS).new
	@cmp -s $(CREDS).new $(CREDS) 2>/dev/null || mv -f $(CREDS).new $(CREDS)
	@rm -f $(CREDS).new

$(BUILD)/tortos: $(SRC) $(CREDS) $(wildcard src/*.h)
	mkdir -p $(BUILD)
	$(CC) $(CFLAGS) -o $@ $(SRC) $(LDLIBS)
